# Generated by Django 3.2 on 2022-01-17 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Things_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.IntegerField()),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=32, unique=True)),
                ('user_passwd', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.IntegerField()),
                ('things_date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='background.things_date')),
            ],
        ),
        migrations.CreateModel(
            name='energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField()),
                ('things_date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='background.things_date')),
            ],
        ),
        migrations.CreateModel(
            name='emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.IntegerField()),
                ('things_date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='background.things_date')),
            ],
        ),
    ]
