# Generated by Django 3.2 on 2022-01-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListThings',
            fields=[
                ('things_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('process', models.IntegerField()),
                ('emotion', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('key', models.TextField()),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='background.user')),
            ],
        ),
    ]
