# Generated by Django 3.2 on 2022-01-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_listthings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='things_date',
        ),
        migrations.RemoveField(
            model_name='process',
            name='things_date',
        ),
        migrations.DeleteModel(
            name='emotion',
        ),
        migrations.DeleteModel(
            name='energy',
        ),
        migrations.DeleteModel(
            name='process',
        ),
        migrations.DeleteModel(
            name='Things_Date',
        ),
    ]
