# Generated by Django 3.2 on 2022-01-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_auto_20220117_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listthings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='listthings',
            name='userid',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='background.user'),
        ),
    ]
