# Generated by Django 3.2 on 2022-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0004_auto_20220117_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listthings',
            name='things_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
