# Generated by Django 3.2 on 2022-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0005_auto_20220117_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listthings',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
