# Generated by Django 3.2 on 2022-01-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0009_alter_listthings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listthings',
            name='date',
            field=models.DateField(),
        ),
    ]
