# Generated by Django 3.2 on 2022-01-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0010_alter_listthings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listthings',
            name='userid',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='background.user'),
        ),
    ]
