# Generated by Django 3.2 on 2022-01-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Things_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.IntegerField()),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proces', models.IntegerField()),
                ('emotion', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('things_date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front.things_date')),
            ],
        ),
    ]
