# Generated by Django 3.2 on 2022-01-17 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.IntegerField()),
                ('things_date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front.things_date')),
            ],
        ),
        migrations.CreateModel(
            name='energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField()),
                ('things_date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front.things_date')),
            ],
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.IntegerField()),
                ('things_date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front.things_date')),
            ],
        ),
        migrations.DeleteModel(
            name='Processing',
        ),
    ]
