# Generated by Django 3.2 on 2022-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listthings',
            name='things_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
